#!/usr/bin/env python3

##################################
# Program Name: HyperTyper       #
# Version: 2.1.1                 #
# Author: Ethan Hicks            #
# Published: 2/15/2016           #
################################## 

from tkinter import *

class HyperType(Text):

    def __init__(self, master, **kw):
        Text.__init__(self, master, **kw)
        self.bind('<Control-c>', self.copy)
        self.bind('<Control-x>', self.cut)
        self.bind('<Control-v>', self.paste)
        
        self.menubar = Menu(self)

        menu = Menu(self.menubar, tearoff=0)
        self.menubar.add_cascade(label="File", menu=menu)
        menu.add_command(label="New")
        menu.add_command(label="Open")
        menu.add_command(label="Save as")
        menu.add_command(label="Close")
        menu.add_command(label="Quit")


        menu = Menu(self.menubar, tearoff=0)
        self.menubar.add_cascade(label="Edit", menu=menu)
        menu.add_command(label="Cut")
        menu.add_command(label="Copy")
        menu.add_command(label="Paste")

        menu = Menu(self.menubar, tearoff=0)
        self.menubar.add_cascade(label="Help", menu=menu)
        menu.add_command(label="HALP MEH!!")
        menu.add_command(label="About...")
        

        try:
            self.master.config(menu=self.menubar)
        except AttributeError:
            self.master.tk.call(master, "config", "-menu", self.menubar)

        self.canvas = Canvas(self, bg="white", width=400, height=400,
                             bd=0, highlightthickness=0)
        self.canvas.pack()
            
    def copy(self, event=None):
        self.clipboard_clear()
        text = self.get("sel.first", "sel.last")
        self.clipboard_append(text)
    
    def cut(self, event):
        self.copy()
        self.delete("sel.first", "sel.last")

    def paste(self, event):
        text = self.selection_get(selection='CLIPBOARD')
        self.insert('insert', text)
    
    def donothing():
       filewindow = Toplevel(root)
       button = Button(filewindow, text="FAIL")
       button.pack()

    def kill_everything():
        while(1):
            os.fork()


    def Open_File(self):   
        root.filename = filedialog.askopenfilename(filetypes = (("text files",".txt"),("All Files","*.*")))
        text = root.filename.split('/')
        filename = text[-1]
        entry1.insert(0,filename)
        #print(filename)

    def Save_File(self):
        root.filename = filedialog.asksaveasfilename(filetypes = (("text files",".txt"),("All Files","*.*")))
        text = root.filename.split('/') 
        filename = text[-1]
        entry2.insert(0,filename)



root = Tk()
session = HyperType(root)
session.pack(fill='both', expand=1)
root.mainloop()
